// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package article

import (
	admin2 "demo-golang/go_homework/week04/internal/data/model/admin"
	blog2 "demo-golang/go_homework/week04/internal/data/model/blog"
	"demo_golang/go_homework/week04/internal/data/repository/admin"
	"demo_golang/go_homework/week04/internal/data/repository/blog"
)

// Injectors from article_wire.go:

func InitPublishMission() *PublishMission {
	userModel := admin.NewUser()
	articleModel := blog.NewArticle()
	publishEvent := NewPublishEvent()
	publishMission := NewPublishMission(userModel, articleModel, publishEvent)
	return publishMission
}

// article_wire.go:

func NewPublishEvent() *PublishEvent {
	return &PublishEvent{}
}

func NewPublishMission(u *admin2.UserModel, a *blog2.ArticleModel, e *PublishEvent) *PublishMission {
	return &PublishMission{u, a, e}
}
